---
title: "Tutorial 4"
author: "Ankur"
date: "29/10/2021"
output: html_document
---
Import library data
```{r}
library(here)
library(tidyverse)
library(dplyr)
library(tmap)
library(sf)
library(janitor)
```


Import CSV data set
```{r}
csv<-read_csv(here::here("Gender Inequality Index (GII).csv"),
              locale=locale(encoding="latin1"),
              na="..", skip=5,col_select = c(1:3,5,7,9,11,13,15,17,19,21,23,25,27)
              ) %>% clean_names()

spec(csv)
```


Import shapefile
```{r}
shp<-st_read(here("World_Countries_(Generalized)","World_Countries__Generalized_.shp"))
```

Create difference data set
```{r}
sapply(csv,class)

csv <- csv %>%
  mutate(Difference_2010_2019 = x2019-x2010)
```


Join CSV and ShapefileData
```{r}
shp<-shp %>%
   left_join(., 
            csv,
            by = c("COUNTRY" = "country"))
```

Plot joined data
```{r}
tmap_mode("plot")
qtm(shp, 
    fill = "Difference_2010_2019", fill.title = "Difference in HDI between 2010 and 2019")
#Added by Yulin
map <- tm_shape(shp) + 
  tm_polygons("Difference_2010_2019", 
              style="pretty",
              palette="-YlOrRd", n = 5,
              midpoint=-0.2,
              title="Difference in HDI between 2010 and 2019",
              alpha = 0.5) +
  tm_layout(title="Fork Map", legend.outside = TRUE, legend.position = c("right", "bottom"))
map
```
